---
- hosts: localhost
  collections:
    - netapp.storagegrid
  vars_files:
    /home/ansible/sg_vars.yaml
  gather_facts: no
  tasks:
  - name: Get grid authorization token
    uri:
      url: "{{ grid_admin_base_url }}/api/v3/authorize"
      method: POST
      body: {
        "username": "{{ grid_username }}",
        "password": "{{ grid_password }}",
        "cookie": false,
        "csrfToken": false
      }
      body_format: json
      validate_certs: false
    register: auth

  - name: Print the token
    ansible.builtin.debug:
     msg:
       - "Bearer {{ auth.json.data }}"

  - name: Limit requests to a QOS of Tenant
    uri:
      url: "{{ grid_admin_base_url }}//api/v3/grid/traffic-classes/policies"
      method: POST
      headers:
                {
                 "accept": "application/json",
                 "Content-Type": "application/json",
                 "Authorization": "Bearer {{ auth.json.data }}"
               }
      body:
        "{{ lookup('file','myfile.json') }}"      
      body_format: json
      validate_certs: false
                                                                                                                     

